version: '3'

services:
  mongo:
    image: mongo:latest

  dynamopm:
    build: 
      context: .
      dockerfile: Dockerfile.dynamopm
    image: ${DOCKER_ORG:-dynamo}/dynamopm:${DOCKER_TAG:-local}
    ports:
      - "8080:8080"
    environment:
      - GREG_DB_URL=mongodb://mongo:27017/
      - AWSAccessKeyId=fakekeyid
      - AWSSecretKey=fakesecretkey
