version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  greg:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GREG_DB_URL=mongodb://mongo:27017/

